### ISSUE TITLE
Edit Alarm config got extra red Error pop-up even function works ok

### ISSUE THREAD

**Issue by alin2k** [opensecuritycontroller/osc-core#382]
### Description
Manage->Alarm->Edit select/deselect Enabled, click OK got red Error! Function ok.
### Expected Behavior
Should not pop-up red Error!
### Actual Behavior
Pop-up red "Error!" after click OK
### Steps to Reproduce
Manage->Alarm->Edit select or deselect Enabled, click OK
### Environment
- OSC Version/Build: **v1Build28**
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by alin2k** [comment]
![editalarmerrs](https://user-images.githubusercontent.com/11319375/28434206-5953ac4e-6d43-11e7-8389-05e6a52ca2d4.PNG)

**Comment by alin2k** [comment]
screenshot attached.

**Comment by arvindn05** [comment]
@alin2k please add logs as well. 

I noticed you closed the issue, is this still a valid bug?

**Comment by emanoelxavier** [comment]
@alin2k I unchecked the status "Reproduced". It should be set only by the person working on the fix to indicate agreement on the bug. This bug is not yet assigned to a owner to be fixed.

**Comment by alin2k** [comment]
show log last 300 (file attached), easily reproduced, log saw something like:
...
2017-07-26 15:34:02,466 [INFO | qtp1155878056-39912| UpdateAlarmWindow]: Error updating alarm
com.vaadin.data.util.MethodProperty$MethodException
        at com.vaadin.data.util.MethodProperty.invokeSetMethod(MethodProperty.java:678)
        at com.vaadin.data.util.MethodProperty.setValue(MethodProperty.java:649)
        at org.osc.core.broker.view.alarm.UpdateAlarmWindow.submitForm(UpdateAlarmWindow.java:97)
        at org.osc.core.broker.window.CRUDBaseWindow.lambda$createWindow$633c848f$1(CRUDBaseWindow.java:69)
        at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vaadin.event.ListenerMethod.receiveEvent(ListenerMethod.java:510)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:200)
        at com.vaadin.event.EventRouter.fireEvent(EventRouter.java:163)
        at com.vaadin.server.AbstractClientConnector.fireEvent(AbstractClientConnector.java:1015)
        at com.vaadin.ui.Button.fireClick(Button.java:377)
        at com.vaadin.ui.Button$1.click(Button.java:54)
        at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:158)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:119)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocation(ServerRpcHandler.java:432)
        at com.vaadin.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:404)
        at com.vaadin.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:273)
        at com.vaadin.server.communication.PushHandler$2.run(PushHandler.java:148)
        at com.vaadin.server.communication.PushHandler.callWithUi(PushHandler.java:240)
        at com.vaadin.server.communication.PushHandler.onMessage(PushHandler.java:494)
        at com.vaadin.server.communication.PushAtmosphereHandler.onMessage(PushAtmosphereHandler.java:87)
        at com.vaadin.server.communication.PushAtmosphereHandler.onRequest(PushAtmosphereHandler.java:77)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:199)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:107)
        at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:180)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:2075)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:571)
        at org.atmosphere.websocket.DefaultWebSocketProcessor$3.run(DefaultWebSocketProcessor.java:333)
        at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:328)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:425)
        at org.atmosphere.container.Jetty9WebSocketHandler.onWebSocketText(Jetty9WebSocketHandler.java:125)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:189)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:66)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:158)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:162)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:376)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:220)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:220)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:256)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.readParse(AbstractWebSocketConnection.java:679)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:511)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:202)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vaadin.data.util.MethodProperty.invokeSetMethod(MethodProperty.java:664)
        ... 58 more

**Comment by alin2k** [comment]
[issue382log300.txt](https://github.com/opensecuritycontroller/osc-core/files/1177489/issue382log300.txt)

**Comment by arvindn05** [comment]
please see and fix for #492.

**Comment by alin2k** [comment]
- [ x] Validated     =>    Verified FIX in Version/Build: v0.8 Build118
