### ISSUE TITLE
NullPointerException (NPE) thrown when updating a DA with a different Service Function Definition, when the SG is binded with the DA

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#392]
### Description
NullPointerException (NPE) thrown when updating a DA with a different Service Function Definition. SG is binded with the DA

### Expected Behavior
The DA edit/update should have been successful with a Passed job

### Actual Behavior
DA edit fails when a different Service Function definition (Image) is selected 

### Steps to Reproduce
Create a DA (e.g. da-1) using Setup > Distributed Appliances. Use an image with 1 nic interface.
Now edit the above DA using a different Service Function Definition. use an image with 2-nic interface.
A warning is received which asks for comfirmation if you want to make the change. 
Click on OK. 
DA edit Job fails - Failed Task shows Null Pointer Exception
Note - That the Sg is binded with this DA

#### Screenshot
![npe-editing-da](https://user-images.githubusercontent.com/28600997/28599143-3986f01a-715d-11e7-978f-a98ca2441e1a.JPG)

#### Logs
[NPE-Editing-DA.txt](https://github.com/opensecuritycontroller/osc-core/files/1175133/NPE-Editing-DA.txt)

java.lang.NullPointerException
	at org.osc.core.broker.service.tasks.conformance.openstack.deploymentspec.OsDAIConformanceCheckMetaTask.executeTransaction(OsDAIConformanceCheckMetaTask.java:194)
	at org.osc.core.broker.service.tasks.TransactionalMetaTask.lambda$execute$0(TransactionalMetaTask.java:51)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.doWork(AbstractTransactionControlImpl.java:161)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.required(AbstractTransactionControlImpl.java:84)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl.required(AbstractTransactionControlImpl.java:263)
	at org.osc.core.broker.service.tasks.TransactionalMetaTask.execute(TransactionalMetaTask.java:50)
	at org.osc.core.broker.job.TaskNode.run(TaskNode.java:308)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:30-g1a88e9b, 2017-07-24T19:39:58Z)
- Cloud Provider Info:
- Plugin Info: NSC SDN Controller, ISM Manager
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by mrajora-1** [comment]
Dmitry checked in a fix in build - 1.0.0-SNAPSHOT (Build:46-gecba891, 2017-08-10T20:04:18Z). 
Tested with the above build and verified that on editing the DA and changing the Service Function Definition, passes now. (Do not see an NPE any more as seen previously). 
Hence we can close this bug.

**Comment by mrajora-1** [comment]
![da-edit-fails-port-not-found](https://user-images.githubusercontent.com/28600997/29195467-7dc6a1fc-7de3-11e7-8050-6b2547e6d66a.JPG)

[Port-Not-found.txt](https://github.com/opensecuritycontroller/osc-core/files/1216586/Port-Not-found.txt)

**Comment by mrajora-1** [comment]
Tried creating the DS without using the floating IP. Then the DA edit passes.

**Comment by mrajora-1** [comment]
@opensecuritycontroller/osc_triage 
The bug is not a repro with NPE any more. 
I will be opening another bug with 'port not found' error.

**Comment by mrajora-1** [comment]
New issue opened for port could not be found error - https://github.com/opensecuritycontroller/osc-core/issues/444
