### ISSUE TITLE
Failed to build osc-core from command line

### ISSUE THREAD

**Issue by vkochan** [opensecuritycontroller/osc-core#395]
### Description
Failed to build osc-core from command line

### Expected Behavior
[INFO] BUILD SUCCESS

### Actual Behavior
[INFO] org.osc.core:osc-export ............................ FAILURE [ 20.051 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:15 min
[INFO] Finished at: 2017-07-27T17:18:52+03:00
[INFO] Final Memory: 122M/1814M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0:export (default) on project osc-export: Default handler for Launcher-Plugin not found in biz.aQute.launcher -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal biz.aQute.bnd:bnd-export-maven-plugin:3.3.0:export (default) on project osc-export: Default handler for Launcher-Plugin not found in biz.aQute.launcher
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
        at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:52)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.IllegalArgumentException: Default handler for Launcher-Plugin not found in biz.aQute.launcher
        at aQute.bnd.build.Project.getHandler(Project.java:2531)
        at aQute.bnd.build.Project.getProjectLauncher(Project.java:2480)
        at aQute.bnd.maven.export.plugin.ExportMojo.export(ExportMojo.java:57)
        at aQute.bnd.maven.export.plugin.ExportMojo.execute(ExportMojo.java:48)
        ... 22 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :osc-export

### Steps to Reproduce
git clone {URL}
cd {repo}/osc-core
mvn clean install -DskipTests -e

### Environment
- OSC Version/Build: 1.0.0-SNAPSHOT
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by emanoelxavier** [comment]
Hi @vkochan  you might be facing this issue because of Maven plugin issue. Please attempt this workaround  https://github.com/opensecuritycontroller/community/blob/master/development/build_run_osc.md#known-maven-compile-error-and-fix and see if fixes the problem.

**Comment by vkochan** [comment]
I really tried but it did not help, so I:

1) Imported project in Eclipse from existing folder
2) Installed bndtools
3) Opened osc-export/server.bndrun
4) Clicked "Resolve" and got the following:
    Unable to resolve <<INITIAL>> version=null:
   missing requirement osc-server

**Comment by emanoelxavier** [comment]
No need to `resolve` at this point. Simply open the server.bdnrun (you already did) and attempt to build from the command line again.

**Comment by arvindn05** [comment]
If its from the CLI, you could be encountering https://github.com/bndtools/bndtools/issues/1294.

You can try the below to resolve the problem. Basically download the launcher jar manually to your bnd-cache folder. The OSC travis build does the same.

https://github.com/opensecuritycontroller/osc-core/blob/master/.travis.yml#L29

`wget -O $HOME/.bnd/default-ws/cnf/cache/3.3.0/bnd-cache/biz.aQute.launcher/biz.aQute.launcher-3.3.0.jar http://central.maven.org/maven2/biz/aQute/bnd/biz.aQute.launcher/3.3.0/biz.aQute.launcher-3.3.0.jar`

**Comment by vkochan** [comment]
Yep!!! That really helped! Thanks a lot !!!

**Comment by bjhargrave** [comment]
> If its from the CLI, you could be encountering bndtools/bndtools#1294.
> 
> You can try the below to resolve the problem. Basically download the launcher jar manually to your bnd-cache folder.

This problem is solved in Bnd 3.4. See https://github.com/bndtools/bnd/pull/1803. So if you update to the 3.4 Bnd maven plugins, they will properly populate the cnf/cache folder as needed.

**Comment by arvindn05** [comment]
@bjhargrave Thanks for the update!
