### ISSUE TITLE
'Port could not be found' error when editing the DA with a different Service Function Definition - DS is created with a floating IP and SG is binded to the DA

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#444]
### Description
'Port not found' error when editing the DA with a different Service Function Definition - DS is created with a floating IP and SG is binded to the DA

### Expected Behavior
The DA edit should have passed

### Actual Behavior
'Port not found' error when editing the DA with a different Service Function Definition - DS is created with a floating IP and SG is binded to the DA

### Steps to Reproduce
Create a VC and an MC
Auto Import an image 
Create a DA. 
Create a DS with a floating IP
Create an SG
Bind the SG to the DA
Now edit the DA and change the Service Function Definition 
An error 'port not found is thrown'  

### Additional Information

Relevant Excerpts from the logs: 
ClientResponseException{message=Port 7edfa34b-19e5-423d-856f-d93c861b6b7a could not be found., status=404, status-code=NOT_FOUND}
at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:38)
at org.openstack4j.core.transport.HttpExceptionHandler.mapException(HttpExceptionHandler.java:23)
at org.openstack4j.core.transport.propagation.PropagateOnStatus.propagate(PropagateOnStatus.java:31)
at org.openstack4j.core.transport.ExecutionOptions.propagate(ExecutionOptions.java:53)
at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:40)
at org.openstack4j.core.transport.HttpEntityHandler.handle(HttpEntityHandler.java:24)
at org.openstack4j.connectors.jersey2.HttpResponseImpl.getEntity(HttpResponseImpl.java:63)
at org.openstack4j.openstack.internal.BaseOpenStackService$Invocation.execute(BaseOpenStackService.java:220)
at org.openstack4j.openstack.networking.internal.FloatingIPServiceImpl.associateToPort(FloatingIPServiceImpl.java:83)
at org.osc.core.broker.rest.client.openstack.openstack4j.Openstack4JNeutron.associateMgmtPortWithFloatingIp(Openstack4JNeutron.java:285)
at org.osc.core.broker.service.tasks.conformance.openstack.deploymentspec.OsSvaCheckFloatingIpTask.executeTransaction(OsSvaCheckFloatingIpTask.java:78)
at org.osc.core.broker.service.tasks.TransactionalMetaTask.lambda$execute$0(TransactionalMetaTask.java:51)
at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.doWork(AbstractTransactionControlImpl.java:161)
at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.required(AbstractTransactionControlImpl.java:84)
at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl.required(AbstractTransactionControlImpl.java:263)
at org.osc.core.broker.service.tasks.TransactionalMetaTask.execute(TransactionalMetaTask.java:50)
at org.osc.core.broker.job.TaskNode.run(TaskNode.java:316)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)

### Environment
- OSC Version/Build: 1.0.0-SNAPSHOT (Build:46-gecba891, 2017-08-10T20:04:18Z).
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![da-edit-fails-port-not-found](https://user-images.githubusercontent.com/28600997/29286393-c2cc2708-80e6-11e7-8c5e-3f8cb0410c52.JPG)

[Port-Not-found.txt](https://github.com/opensecuritycontroller/osc-core/files/1223130/Port-Not-found.txt)

**Comment by mrajora-1** [comment]
Related to bug - https://github.com/opensecuritycontroller/osc-core/issues/392
