### ISSUE TITLE
Get an error - 'Fail to populate Security Group Table' while running VC automation tests

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#446]
### Description
Get an error - 'Fail to populate Security Group Table' while running VC automation tests
The error appears in the OSC UI (several errors of the same kind)

### Expected Behavior
Should not be seeing the error 'Fail to populate Security Group Table' while running VC automation tests

### Actual Behavior
Get an error - 'Fail to populate Security Group Table (Open Security Controller:Virtualization Connector with id:xx not found)' while running VC automation tests. The VC id keeps changing as the tests run. 

### Steps to Reproduce
Login to OSC UI and navigate to VC tab.
Run VC automation tests
Somewhere along the way start seeing errors with different VC ids. 

### Additional Information
We run VC.robot while OSC UI Virtualization Connectors page is open - the UI wants to refresh the view of VCs he got after any change - it looks like the frequent changes of create/delete that are generated from the automation (VC.robot) are too much for the UI to handle.
Probably the create/delete/get operations are not atomic (or not synchronized) and hence the UI complains since he cannot present a VC that he think he can present.

Probably the UI get that there is a VC - in the middle of deletion of this VC and when he wants to display it it fails to find it.  (the delete finished)

### Environment
- OSC Version/Build: 1.0.0-SNAPSHOT (Build:49-ged86223, 2017-08-12T07:19:44Z)
- Cloud Provider Info:
- Plugin Info:
- Other:
Excerpt from log: VmidcBrokerValidationException

2017-08-17 18:39:11,043 [ERROR| pool-13-thread-1| VirtualizationConnectorView]: Fail to populate Security Group table
org.osc.core.broker.service.exceptions.VmidcBrokerValidationException: Open Security Controller: Virtualization Connector with Id: 15  is not found.
	at org.osc.core.broker.service.securitygroup.ListSecurityGroupByVcService.validate(ListSecurityGroupByVcService.java:70)
	at org.osc.core.broker.service.securitygroup.ListSecurityGroupByVcService.exec(ListSecurityGroupByVcService.java:46)
	at org.osc.core.broker.service.securitygroup.ListSecurityGroupByVcService.exec(ListSecurityGroupByVcService.java:37)
	at org.osc.core.broker.service.ServiceDispatcher.lambda$dispatch$0(ServiceDispatcher.java:92)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.doWork(AbstractTransactionControlImpl.java:161)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.required(AbstractTransactionControlImpl.java:84)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl.required(AbstractTransactionControlImpl.java:263)
	at org.osc.core.broker.service.ServiceDispatcher.dispatch(ServiceDispatcher.java:92)
	at org.osc.core.broker.view.vc.VirtualizationConnectorView.populateChildTable(VirtualizationConnectorView.java:257)
	at org.osc.core.broker.view.CRUDBaseView.parentTableClicked(CRUDBaseView.java:498)
	at org.osc.core.broker.view.vc.VirtualizationConnectorView.parentTableClicked(VirtualizationConnectorView.java:428)
	at org.osc.core.broker.view.CRUDBaseView.selectFirstParentItemIfExists(CRUDBaseView.java:664)
	at org.osc.core.broker.view.CRUDBaseView.access$000(CRUDBaseView.java:69)
	at org.osc.core.broker.view.CRUDBaseView$2.containerItemSetChange(CRUDBaseView.java:287)
	at com.vaadin.ui.AbstractSelect.fireItemSetChange(AbstractSelect.java:1743)
	at com.vaadin.ui.AbstractSelect.containerItemSetChange(AbstractSelect.java:1713)
	at com.vaadin.ui.CustomTable.containerItemSetChange(CustomTable.java:4512)
	at com.vaadin.data.util.AbstractContainer.fireItemSetChange(AbstractContainer.java:246)
	at com.vaadin.data.util.AbstractInMemoryContainer.fireItemsAdded(AbstractInMemoryContainer.java:1012)
	at com.vaadin.data.util.AbstractInMemoryContainer.fireItemAdded(AbstractInMemoryContainer.java:994)
	at com.vaadin.data.util.AbstractInMemoryContainer.internalAddItemAfter(AbstractInMemoryContainer.java:924)
	at com.vaadin.data.util.AbstractInMemoryContainer.internalAddItemAt(AbstractInMemoryContainer.java:952)
	at com.vaadin.data.util.AbstractBeanContainer.addItemAt(AbstractBeanContainer.java:569)
	at com.vaadin.data.util.BeanContainer.addItemAt(BeanContainer.java:125)
	at org.osc.core.broker.view.util.ViewUtil.updateTableContainer(ViewUtil.java:234)
	at org.osc.core.broker.view.CRUDBaseView.updateParentContainer(CRUDBaseView.java:649)
	at org.osc.core.broker.view.CRUDBaseView.syncParentTable(CRUDBaseView.java:586)
	at org.osc.core.broker.view.CRUDBaseView.syncTables(CRUDBaseView.java:548)
	at org.osc.core.broker.view.MainUI$8.run(MainUI.java:567)
	at com.vaadin.ui.UI.accessSynchronously(UI.java:1392)
	at com.vaadin.ui.UI$4.run(UI.java:1458)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.vaadin.server.VaadinService.runPendingAccessTasks(VaadinService.java:1846)
	at com.vaadin.server.VaadinSession.unlock(VaadinSession.java:992)
	at com.vaadin.server.VaadinService.ensureAccessQueuePurged(VaadinService.java:1809)
	at com.vaadin.server.VaadinService.accessSession(VaadinService.java:1775)
	at com.vaadin.server.VaadinSession.access(VaadinSession.java:1384)
	at com.vaadin.ui.UI.access(UI.java:1455)
	at org.osc.core.broker.view.MainUI.receiveBroadcast(MainUI.java:555)
	at org.osc.core.broker.util.BroadcasterUtil$1.run(BroadcasterUtil.java:93)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![fail-to-populate-sg-table](https://user-images.githubusercontent.com/28600997/29538589-4ead60b8-867b-11e7-8f99-c7dd48242e16.JPG)

[securityBroker (2).txt](https://github.com/opensecuritycontroller/osc-core/files/1240190/securityBroker.2.txt)

**Comment by arvindn05** [comment]
Looks like related only to automation runs. We need to independently reproduce apart from the robot script. @mrajora-1 please add more info

**Comment by mrajora-1** [comment]
Tested with 0.8 with Yaron. Do not see the above issue occurring any more.
