### ISSUE TITLE
Upon fresh ovf install RestClient errors on screen and in boot.log

### ISSUE THREAD

**Issue by dmitryintel** [opensecuritycontroller/osc-core#539]
### Description

Upon fresh ovf install, multiple RestClient exceptions show up in **/var/log/boot.log** and on the Console screen. 

### Expected Behavior

The exceptions should go to **/opt/vmidc/log/securityBorker.log** (if they happen) and should not be seen in the console or in **boot.log**.

### Actual Behavior

See the description.

### Steps to Reproduce

Install an ovf and watch the console in VSphere.

### Additional Information

The exceptions themselves may well have been happening before Oct 6, 2017, even with commits  at or before [3b67a0ee](https://github.com/opensecuritycontroller/osc-core/commit/3b67a0ee160bf7f599e617e3bd7c0ea01215e560). But with our slf4j logging changes they started appearing on the console. 

Typical exception:

18:54:21.415 [main] DEBUG org.osc.core.broker.rest.client.RestBaseClient - Error invoking getResources
org.osc.core.broker.service.exceptions.RestClientException: Failed to GET resource: 'https://localhost:8090/api/server/v1/serverManagement/status'.
Reason: 'javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)'.
Response Code: null.
Response: 'null'.
        at org.osc.core.broker.rest.client.RestBaseClient.createRestClientException(RestBaseClient.java:504)
        at org.osc.core.broker.rest.client.RestBaseClient.getResource(RestBaseClient.java:269)
        at org.osc.core.broker.rest.client.RestBaseClient.getResource(RestBaseClient.java:246)
        at org.osc.core.broker.rest.client.RestBaseClient.getResource(RestBaseClient.java:241)
        at org.osc.core.server.control.ServerControl.getServerStatusResponse(ServerControl.java:356)
        at org.osc.core.server.control.ServerControl.isRunningServer(ServerControl.java:279)
        at org.osc.core.server.control.ServerControl.access$000(ServerControl.java:52)
        at org.osc.core.server.control.ServerControl$1.isRunning(ServerControl.java:102)
        at org.osc.core.broker.util.ServerUtil.startServerProcess(ServerUtil.java:290)
        at org.osc.core.broker.util.ServerUtil.startServerProcess(ServerUtil.java:274)
        at org.osc.core.server.control.ServerControl.main(ServerControl.java:99)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:272)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:96)
        at org.osc.core.broker.rest.client.RestBaseClient.getResource(RestBaseClient.java:255)
        ... 9 common frames omitted
Caused by: javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)
        at org.glassfish.jersey.client.internal.HttpUrlConnector$3.run(HttpUrlConnector.java:299)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
        at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:293)
        at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
        at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
		at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:399)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.access$000(HttpUrlConnector.java:96)
        at org.glassfish.jersey.client.internal.HttpUrlConnector$3.run(HttpUrlConnector.java:297)
        ... 20 common frames omitted
Fail to connect to running server. Assuming not running: org.osc.core.broker.service.exceptions.RestClientException: Failed to GET resource: 'https://localhost:8090/api/server/v1/serverManagement/status'.
Reason: 'javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused (Connection refused)'.
Response Code: null.
Response: 'null'.
Check if server is running ...
18:54:21.950 [jersey-client-async-executor-0] ERROR org.osc.core.broker.rest.client.RestBaseClient - Request invocation failed. Problem with parsing response to json
18:54:21.951 [main] DEBUG org.osc.core.broker.rest.client.RestBaseClient - Error invoking getResources

### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT, Build:112-g42e1905.
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [x] Validated     =>    Verified in Version/Build:  **v0.8 Build#118** OVF **fixed**:
1)console not seeing any RestClient text
2)"grep -i RestClient /var/log/boot.log" returns none.
3)In OSC CLI "show log last 800" did see:
...
2017-10-17 16:44:25,494 [WARN | main| o.o.c.s.c.ServerControl]: Fail to connect to running server. Assuming not running: org.osc.core.broker.service.exceptions.RestClientException: Failed to GET resource: 'https://localhost:8090/api/server/v1/serverManagement/status'.
Reason: 'null'.
Response Code: 404.
Response: '<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 </title>
</head>
<body>
<h2>HTTP ERROR: 404</h2>
<p>Problem accessing /api/server/v1/serverManagement/status. Reason:
<pre>    Not Found</pre></p>
<hr />
</body>
</html>
'.

**Comment by alin2k** [comment]
QA validated and can close the issue?
