### ISSUE TITLE
When binding an SG with 2 services, using the SFC binding API, the first time Job fails with error - Transaction Rolled back due to a failure

### ISSUE THREAD

**Issue by mrajora-1** [opensecuritycontroller/osc-core#547]
### Description
When binding an SG with 2 services, using the SFC binding API, the first time Job fails with error - Transaction Rolled back due to a failure. Sync of SG makes the job pass
### Expected Behavior
When binding an SG with 2 services, using the SFC binding API, the first time Job fails with error - Transaction Rolled back due to a failure. 
### Actual Behavior
SG sync job should have passed in the initial attempt. 
### Steps to Reproduce
- Create VC (using SFC), MC, 2DA, 2DSs, SG
- Bind the SG using SFC API. 
- SG Sync job fails with error - Transaction Rolled back due to a failure

### Additional Information
Log Excerpt

org.osgi.service.transaction.control.TransactionRolledBackException: The transaction rolled back due to a failure
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.doWork(AbstractTransactionControlImpl.java:208)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.required(AbstractTransactionControlImpl.java:84)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl.required(AbstractTransactionControlImpl.java:263)
	at org.osc.core.broker.service.tasks.TransactionalTask.execute(TransactionalTask.java:44)
	at org.osc.core.broker.job.TaskNode.run(TaskNode.java:317)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.service.transaction.control.TransactionException: An error occurred when committing the connection
	at org.apache.aries.tx.control.jpa.local.impl.TxContextBindingEntityManager$1.commit(TxContextBindingEntityManager.java:110)
	at org.apache.aries.tx.control.service.local.impl.TransactionContextImpl.lambda$finish$1(TransactionContextImpl.java:191)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.apache.aries.tx.control.service.local.impl.TransactionContextImpl.finish(TransactionContextImpl.java:185)
	at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.doWork(AbstractTransactionControlImpl.java:200)
	... 9 common frames omitted
Caused by: javax.persistence.RollbackException: Error while committing the transaction
	at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:75)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:71)
	at org.apache.aries.tx.control.jpa.local.impl.TxContextBindingEntityManager$1.commit(TxContextBindingEntityManager.java:108)
	... 14 common frames omitted
### Environment
- OSC Version/Build: Version: 1.0.0-SNAPSHOT (Build:112-g42e1905, 2017-10-11T18:46:02Z)
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [x] In Progress
- [ ] Validated     =>    Verified in Version/Build: 

![transaction-rolled-back-failure](https://user-images.githubusercontent.com/28600997/31559325-15a5a61e-b005-11e7-80cb-51bbe91709c2.JPG)

[securityBroker-DS.log](https://github.com/opensecuritycontroller/osc-core/files/1383507/securityBroker-DS.log)

**Comment by arvindn05** [comment]
DE5348

**Comment by mrajora-1** [comment]
Verified with Build - Version: 1.0.0-SNAPSHOT (Build:140-gb301029, 2017-10-24T07:22:46Z)

[securityBroker-fix-transaction-rollback-error-binding-sfc.log](https://github.com/opensecuritycontroller/osc-core/files/1412869/securityBroker-fix-transaction-rollback-error-binding-sfc.log)
