### ISSUE TITLE
Removing VMs from bound Security Group results in referrential integrity error

### ISSUE THREAD

**Issue by dmitryintel** [opensecuritycontroller/osc-core#627]
### Description
Deleting VM members from SG while it is bound sometimes fails with referential integrity exceptions.

### Expected Behavior
Should be able to edit SG members while bound.

### Actual Behavior

Removing the original VM fails. 

### Steps to Reproduce
Openstack (mitaka) with two VMS is required. Reproduced on Newton with NSC.

- Create a Security Group with one Virtual Machine. 
- Bind.
- Edit the a second VM while bound. 
- Remove the original VM while bound.
  (or try removing both)

### Additional Information
Stack trace:

2018-01-05 18:48:57,205 [INFO | isc-task-pool-5| o.o.c.b.s.t.c.o.s.SecurityGroupMemberDeleteTask]: Deleting Security Group member from SGNew01
2018-01-05 18:48:57,274 [WARN | isc-task-pool-5| o.o.c.b.j.TaskNode]: Task TaskNode [task=[null], state=RUNNING, status=PASSED, guard=ALL_PREDECESSORS_SUCCEEDED] Failed
org.osgi.service.transaction.control.TransactionRolledBackException: The transaction rolled back due to a failure
        at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.doWork(AbstractTransactionControlImpl.java:208)
        at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.required(AbstractTransactionControlImpl.java:84)
        at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl.required(AbstractTransactionControlImpl.java:263)
        at org.osc.core.broker.service.tasks.TransactionalTask.execute(TransactionalTask.java:44)
        at org.osc.core.broker.job.TaskNode.run(TaskNode.java:317)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.osgi.service.transaction.control.TransactionException: An error occurred when committing the connection
        at org.apache.aries.tx.control.jpa.local.impl.TxContextBindingEntityManager$1.commit(TxContextBindingEntityManager.java:110)
        at org.apache.aries.tx.control.service.local.impl.TransactionContextImpl.lambda$finish$1(TransactionContextImpl.java:191)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at org.apache.aries.tx.control.service.local.impl.TransactionContextImpl.finish(TransactionContextImpl.java:185)
        at org.apache.aries.tx.control.service.common.impl.AbstractTransactionControlImpl$TransactionBuilderImpl.doWork(AbstractTransactionControlImpl.java:200)
        ... 9 common frames omitted
Caused by: javax.persistence.RollbackException: Error while committing the transaction
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:75)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:71)
        at org.apache.aries.tx.control.jpa.local.impl.TxContextBindingEntityManager$1.commit(TxContextBindingEntityManager.java:108)
        ... 14 common frames omitted
Caused by: javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:147)
        at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:155)
        at org.hibernate.internal.ExceptionConverterImpl.convertCommitException(ExceptionConverterImpl.java:56)
        ... 16 common frames omitted
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
        at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
        at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3315)
        at org.hibernate.persister.entity.AbstractEntityPersister.delete(AbstractEntityPersister.java:3552)
        at org.hibernate.action.internal.EntityDeleteAction.execute(EntityDeleteAction.java:99)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:586)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:460)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
        at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
        at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1428)
        at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:484)
        at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3190)
        at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2404)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:467)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:146)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
        at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:220)
        at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:68)
        ... 15 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_DAI_VMP_VMP: PUBLIC.DISTRIBUTED_APPLIANCE_INSTANCE_VM_PORT FOREIGN KEY(VM_PORT_FK) REFERENCES PUBLIC.VM_PORT(ID) (18)"; SQL statement:
delete from VM_PORT where id=? and version=? [23503-194]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
        at org.h2.message.DbException.get(DbException.java:179)
        at org.h2.message.DbException.get(DbException.java:155)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:425)
        at org.h2.constraint.ConstraintReferential.checkRowRefTable(ConstraintReferential.java:442)
        at org.h2.constraint.ConstraintReferential.checkRow(ConstraintReferential.java:317)

### Environment
- OSC Version/Build: 1.0.0
- Cloud Provider Info:
- Plugin Info:
- Other:

### Status
- [ ] Reproduced
- [ ] In Progress
- [ ] Validated     =>    Verified in Version/Build:

**Comment by sudhirappaji** [comment]
@dmitryintel , this is already assigned to you.
